#!/bin/bash

# TODO: Improve.

function expect() {
  expected=$1
  shift
  $@
  actual=$?
  if [[ $expected -ne $actual ]]; then
    echo "Expected $expected, got $actual with program: $@"
    exit 1
  fi
}

function expectIO() {
  expected=$1
  shift
  input=$1
  shift
  output=$1
  shift
  actual_output="$(echo -n "$input" | $@ 2>&1)"
  actual=$?
  if [[ $expected -ne $actual ]]; then
    echo "Expected $expected, got $actual with program: $@"
    exit 1
  fi
  if [[ "$output" != "$actual_output" ]]; then
    echo "Expected different output with program: $@"
    echo "Expected:"
    echo "$output"
    echo "Got:"
    echo "$actual_output"
    exit 1
  fi
}

expect 0 ./true
expect 1 ./false
expect 1 ./argc
expect 2 ./argc a
expect 0 ./stdint
expect 0 ./stdarg
expect 2 ./assert
expectIO 1 "" $'Assert failure:\n  File: assert-fail-test.c\n  Func: main\n  Line: 4' ./assert-fail
expect 3 ./string
expect 5 ./strlen abcde
expect 0 ./strlen ""
expect 7 ./strlen zyxwvut
expect 5 ./setjmp
expect 0 ./malloc
expectIO 0 "" $'abcd\nefgh' ./chario "abcd" "efgh"
expectIO 0 $'abcd\nefgh' $'abcd\nefgh' ./echo
expect 0 ./ctype
expectIO 0 "" $'abc, defgh, i' ./printf
expect 0 ./sprintf
expect 0 ./qsort
expect 0 ./bsearch
expect 0 ./strdup
expect 0 ./atomic-flag
expect 0 ./mtx
expectIO 0 "" "Sum is: 1000000" '' ./threads2
expect 0 ./tls
expect 0 ./tss
expect 0 ./math
expect 0 ./iso646
expect 0 ./time
expectIO 136 "" $'S8' '' ./signal
TEST="123" TEST2="456" expectIO 0 "" $'TEST is: TEST=123\nTEST2 is: 456' ./env
TEST="" TEST2="" expectIO 0 "" $'TEST is: TEST=\nTEST2 is: ' ./env

touch test-data/unreadable
chmod 000 test-data/unreadable
expect 0 ./file
# Run file twice, in case it changed any files.
expect 0 ./file

thr_output="$(./threads)"
for i in `seq 5`; do
  if [[ "$i" != "$(echo "$thr_output" | grep -c "Running, val: $i")" ]]; then
    echo "Invalid output from ./threads (with $i)"
    exit 1
  fi
done
