#!/bin/bash

# TODO: Improve.

function expect() {
  expected=$1
  shift
  $@
  actual=$?
  if [[ $expected -ne $actual ]]; then
    echo "Expected $expected, got $actual with program: $@"
    exit 1
  fi
}

function expectIO() {
  expected=$1
  shift
  input=$1
  shift
  output=$1
  shift
  actual_output="$(echo -n "$input" | $@ 2>&1)"
  actual=$?
  if [[ $expected -ne $actual ]]; then
    echo "Expected $expected, got $actual with program: $@"
    exit 1
  fi
  if [[ "$output" != "$actual_output" ]]; then
    echo "Expected different output with program: $@"
    echo "Expected:"
    echo "$output"
    echo "Got:"
    echo "$actual_output"
    exit 1
  fi
}

expect 0 ./true
expect 1 ./false
expect 1 ./argc
expect 2 ./argc a
expect 0 ./stdint
expect 0 ./stdarg
expect 2 ./assert
expectIO 1 "" $'Assert failure:\n  File: assert-fail.c\n  Func: main\n  Line: 4' ./assert-fail
expect 3 ./string
expect 5 ./strlen abcde
expect 0 ./strlen ""
expect 7 ./strlen zyxwvut
expect 5 ./setjmp
expect 0 ./malloc
expectIO 0 "" $'abcd\nefgh' ./chario "abcd" "efgh"
expectIO 0 $'abcd\nefgh' $'abcd\nefgh' ./echo
expect 0 ./ctype
expectIO 0 "" $'abc, defgh, i' ./printf
expect 0 ./sprintf
expect 0 ./qsort
expect 0 ./bsearch
expect 0 ./strdup
expect 0 ./atomic_flag
expect 0 ./mtx
expect 0 ./threads
expect 0 ./threads2
