#!/bin/bash

# TODO: Improve.

function expect() {
  expected=$1
  shift
  $@
  actual=$?
  if [[ $expected -ne $actual ]]; then
    echo "Expected $expected, got $actual with program: $@"
    exit 1
  fi
}

expect 0 ./true
expect 1 ./false
expect 1 ./argc
expect 2 ./argc a
expect 0 ./stdint
expect 0 ./stdarg
expect 2 ./assert
expect 1 ./assert-fail
expect 3 ./string
expect 5 ./strlen abcde
expect 0 ./strlen ""
expect 7 ./strlen zyxwvut
expect 5 ./setjmp
expect 0 ./malloc
